// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/EricomSoftwareLtd/ridge-go/models"
)

// NewCreateClusterNodePoolParams creates a new CreateClusterNodePoolParams object
// with the default values initialized.
func NewCreateClusterNodePoolParams() *CreateClusterNodePoolParams {
	var ()
	return &CreateClusterNodePoolParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateClusterNodePoolParamsWithTimeout creates a new CreateClusterNodePoolParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateClusterNodePoolParamsWithTimeout(timeout time.Duration) *CreateClusterNodePoolParams {
	var ()
	return &CreateClusterNodePoolParams{

		timeout: timeout,
	}
}

// NewCreateClusterNodePoolParamsWithContext creates a new CreateClusterNodePoolParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateClusterNodePoolParamsWithContext(ctx context.Context) *CreateClusterNodePoolParams {
	var ()
	return &CreateClusterNodePoolParams{

		Context: ctx,
	}
}

// NewCreateClusterNodePoolParamsWithHTTPClient creates a new CreateClusterNodePoolParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateClusterNodePoolParamsWithHTTPClient(client *http.Client) *CreateClusterNodePoolParams {
	var ()
	return &CreateClusterNodePoolParams{
		HTTPClient: client,
	}
}

/*CreateClusterNodePoolParams contains all the parameters to send to the API endpoint
for the create cluster node pool operation typically these are written to a http.Request
*/
type CreateClusterNodePoolParams struct {

	/*Body*/
	Body *models.NodePoolCreate
	/*Cluster
	  The identifier of a cluster.

	*/
	Cluster string
	/*Org
	  The organization identifier

	*/
	Org string
	/*Project
	  The project identifier

	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create cluster node pool params
func (o *CreateClusterNodePoolParams) WithTimeout(timeout time.Duration) *CreateClusterNodePoolParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create cluster node pool params
func (o *CreateClusterNodePoolParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create cluster node pool params
func (o *CreateClusterNodePoolParams) WithContext(ctx context.Context) *CreateClusterNodePoolParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create cluster node pool params
func (o *CreateClusterNodePoolParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create cluster node pool params
func (o *CreateClusterNodePoolParams) WithHTTPClient(client *http.Client) *CreateClusterNodePoolParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create cluster node pool params
func (o *CreateClusterNodePoolParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create cluster node pool params
func (o *CreateClusterNodePoolParams) WithBody(body *models.NodePoolCreate) *CreateClusterNodePoolParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create cluster node pool params
func (o *CreateClusterNodePoolParams) SetBody(body *models.NodePoolCreate) {
	o.Body = body
}

// WithCluster adds the cluster to the create cluster node pool params
func (o *CreateClusterNodePoolParams) WithCluster(cluster string) *CreateClusterNodePoolParams {
	o.SetCluster(cluster)
	return o
}

// SetCluster adds the cluster to the create cluster node pool params
func (o *CreateClusterNodePoolParams) SetCluster(cluster string) {
	o.Cluster = cluster
}

// WithOrg adds the org to the create cluster node pool params
func (o *CreateClusterNodePoolParams) WithOrg(org string) *CreateClusterNodePoolParams {
	o.SetOrg(org)
	return o
}

// SetOrg adds the org to the create cluster node pool params
func (o *CreateClusterNodePoolParams) SetOrg(org string) {
	o.Org = org
}

// WithProject adds the project to the create cluster node pool params
func (o *CreateClusterNodePoolParams) WithProject(project string) *CreateClusterNodePoolParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the create cluster node pool params
func (o *CreateClusterNodePoolParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *CreateClusterNodePoolParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param cluster
	if err := r.SetPathParam("cluster", o.Cluster); err != nil {
		return err
	}

	// path param org
	if err := r.SetPathParam("org", o.Org); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
