// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/EricomSoftwareLtd/ridge-go/models"
)

// CreateClusterTokenReader is a Reader for the CreateClusterToken structure.
type CreateClusterTokenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateClusterTokenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateClusterTokenOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateClusterTokenBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateClusterTokenForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateClusterTokenNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateClusterTokenOK creates a CreateClusterTokenOK with default headers values
func NewCreateClusterTokenOK() *CreateClusterTokenOK {
	return &CreateClusterTokenOK{}
}

/*CreateClusterTokenOK handles this case with default header values.

OK
*/
type CreateClusterTokenOK struct {
	Payload *models.TokenCreated
}

func (o *CreateClusterTokenOK) Error() string {
	return fmt.Sprintf("[POST /orgs/{org}/projects/{project}/clusters/{cluster}/tokens][%d] createClusterTokenOK  %+v", 200, o.Payload)
}

func (o *CreateClusterTokenOK) GetPayload() *models.TokenCreated {
	return o.Payload
}

func (o *CreateClusterTokenOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TokenCreated)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateClusterTokenBadRequest creates a CreateClusterTokenBadRequest with default headers values
func NewCreateClusterTokenBadRequest() *CreateClusterTokenBadRequest {
	return &CreateClusterTokenBadRequest{}
}

/*CreateClusterTokenBadRequest handles this case with default header values.

Bad request parameter
*/
type CreateClusterTokenBadRequest struct {
	Payload string
}

func (o *CreateClusterTokenBadRequest) Error() string {
	return fmt.Sprintf("[POST /orgs/{org}/projects/{project}/clusters/{cluster}/tokens][%d] createClusterTokenBadRequest  %+v", 400, o.Payload)
}

func (o *CreateClusterTokenBadRequest) GetPayload() string {
	return o.Payload
}

func (o *CreateClusterTokenBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateClusterTokenForbidden creates a CreateClusterTokenForbidden with default headers values
func NewCreateClusterTokenForbidden() *CreateClusterTokenForbidden {
	return &CreateClusterTokenForbidden{}
}

/*CreateClusterTokenForbidden handles this case with default header values.

Forbidden
*/
type CreateClusterTokenForbidden struct {
	Payload string
}

func (o *CreateClusterTokenForbidden) Error() string {
	return fmt.Sprintf("[POST /orgs/{org}/projects/{project}/clusters/{cluster}/tokens][%d] createClusterTokenForbidden  %+v", 403, o.Payload)
}

func (o *CreateClusterTokenForbidden) GetPayload() string {
	return o.Payload
}

func (o *CreateClusterTokenForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateClusterTokenNotFound creates a CreateClusterTokenNotFound with default headers values
func NewCreateClusterTokenNotFound() *CreateClusterTokenNotFound {
	return &CreateClusterTokenNotFound{}
}

/*CreateClusterTokenNotFound handles this case with default header values.

Resource not found
*/
type CreateClusterTokenNotFound struct {
	Payload string
}

func (o *CreateClusterTokenNotFound) Error() string {
	return fmt.Sprintf("[POST /orgs/{org}/projects/{project}/clusters/{cluster}/tokens][%d] createClusterTokenNotFound  %+v", 404, o.Payload)
}

func (o *CreateClusterTokenNotFound) GetPayload() string {
	return o.Payload
}

func (o *CreateClusterTokenNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
