// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/EricomSoftwareLtd/ridge-go/models"
)

// CreateClusterNodePoolReader is a Reader for the CreateClusterNodePool structure.
type CreateClusterNodePoolReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateClusterNodePoolReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateClusterNodePoolOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateClusterNodePoolBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateClusterNodePoolForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateClusterNodePoolNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateClusterNodePoolOK creates a CreateClusterNodePoolOK with default headers values
func NewCreateClusterNodePoolOK() *CreateClusterNodePoolOK {
	return &CreateClusterNodePoolOK{}
}

/*CreateClusterNodePoolOK handles this case with default header values.

OK
*/
type CreateClusterNodePoolOK struct {
	Payload *models.NodePool
}

func (o *CreateClusterNodePoolOK) Error() string {
	return fmt.Sprintf("[POST /orgs/{org}/projects/{project}/clusters/{cluster}/node-pools][%d] createClusterNodePoolOK  %+v", 200, o.Payload)
}

func (o *CreateClusterNodePoolOK) GetPayload() *models.NodePool {
	return o.Payload
}

func (o *CreateClusterNodePoolOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NodePool)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateClusterNodePoolBadRequest creates a CreateClusterNodePoolBadRequest with default headers values
func NewCreateClusterNodePoolBadRequest() *CreateClusterNodePoolBadRequest {
	return &CreateClusterNodePoolBadRequest{}
}

/*CreateClusterNodePoolBadRequest handles this case with default header values.

Bad request parameter
*/
type CreateClusterNodePoolBadRequest struct {
	Payload string
}

func (o *CreateClusterNodePoolBadRequest) Error() string {
	return fmt.Sprintf("[POST /orgs/{org}/projects/{project}/clusters/{cluster}/node-pools][%d] createClusterNodePoolBadRequest  %+v", 400, o.Payload)
}

func (o *CreateClusterNodePoolBadRequest) GetPayload() string {
	return o.Payload
}

func (o *CreateClusterNodePoolBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateClusterNodePoolForbidden creates a CreateClusterNodePoolForbidden with default headers values
func NewCreateClusterNodePoolForbidden() *CreateClusterNodePoolForbidden {
	return &CreateClusterNodePoolForbidden{}
}

/*CreateClusterNodePoolForbidden handles this case with default header values.

Forbidden
*/
type CreateClusterNodePoolForbidden struct {
	Payload string
}

func (o *CreateClusterNodePoolForbidden) Error() string {
	return fmt.Sprintf("[POST /orgs/{org}/projects/{project}/clusters/{cluster}/node-pools][%d] createClusterNodePoolForbidden  %+v", 403, o.Payload)
}

func (o *CreateClusterNodePoolForbidden) GetPayload() string {
	return o.Payload
}

func (o *CreateClusterNodePoolForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateClusterNodePoolNotFound creates a CreateClusterNodePoolNotFound with default headers values
func NewCreateClusterNodePoolNotFound() *CreateClusterNodePoolNotFound {
	return &CreateClusterNodePoolNotFound{}
}

/*CreateClusterNodePoolNotFound handles this case with default header values.

Resource not found
*/
type CreateClusterNodePoolNotFound struct {
	Payload string
}

func (o *CreateClusterNodePoolNotFound) Error() string {
	return fmt.Sprintf("[POST /orgs/{org}/projects/{project}/clusters/{cluster}/node-pools][%d] createClusterNodePoolNotFound  %+v", 404, o.Payload)
}

func (o *CreateClusterNodePoolNotFound) GetPayload() string {
	return o.Payload
}

func (o *CreateClusterNodePoolNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
