// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/EricomSoftwareLtd/ridge-go/models"
)

// NewCreateClusterTokenParams creates a new CreateClusterTokenParams object
// with the default values initialized.
func NewCreateClusterTokenParams() *CreateClusterTokenParams {
	var ()
	return &CreateClusterTokenParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateClusterTokenParamsWithTimeout creates a new CreateClusterTokenParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateClusterTokenParamsWithTimeout(timeout time.Duration) *CreateClusterTokenParams {
	var ()
	return &CreateClusterTokenParams{

		timeout: timeout,
	}
}

// NewCreateClusterTokenParamsWithContext creates a new CreateClusterTokenParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateClusterTokenParamsWithContext(ctx context.Context) *CreateClusterTokenParams {
	var ()
	return &CreateClusterTokenParams{

		Context: ctx,
	}
}

// NewCreateClusterTokenParamsWithHTTPClient creates a new CreateClusterTokenParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateClusterTokenParamsWithHTTPClient(client *http.Client) *CreateClusterTokenParams {
	var ()
	return &CreateClusterTokenParams{
		HTTPClient: client,
	}
}

/*CreateClusterTokenParams contains all the parameters to send to the API endpoint
for the create cluster token operation typically these are written to a http.Request
*/
type CreateClusterTokenParams struct {

	/*Body*/
	Body *models.TokenCreate
	/*Cluster
	  The identifier of a cluster.

	*/
	Cluster string
	/*Org
	  The organization identifier

	*/
	Org string
	/*Project
	  The project identifier

	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create cluster token params
func (o *CreateClusterTokenParams) WithTimeout(timeout time.Duration) *CreateClusterTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create cluster token params
func (o *CreateClusterTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create cluster token params
func (o *CreateClusterTokenParams) WithContext(ctx context.Context) *CreateClusterTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create cluster token params
func (o *CreateClusterTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create cluster token params
func (o *CreateClusterTokenParams) WithHTTPClient(client *http.Client) *CreateClusterTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create cluster token params
func (o *CreateClusterTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create cluster token params
func (o *CreateClusterTokenParams) WithBody(body *models.TokenCreate) *CreateClusterTokenParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create cluster token params
func (o *CreateClusterTokenParams) SetBody(body *models.TokenCreate) {
	o.Body = body
}

// WithCluster adds the cluster to the create cluster token params
func (o *CreateClusterTokenParams) WithCluster(cluster string) *CreateClusterTokenParams {
	o.SetCluster(cluster)
	return o
}

// SetCluster adds the cluster to the create cluster token params
func (o *CreateClusterTokenParams) SetCluster(cluster string) {
	o.Cluster = cluster
}

// WithOrg adds the org to the create cluster token params
func (o *CreateClusterTokenParams) WithOrg(org string) *CreateClusterTokenParams {
	o.SetOrg(org)
	return o
}

// SetOrg adds the org to the create cluster token params
func (o *CreateClusterTokenParams) SetOrg(org string) {
	o.Org = org
}

// WithProject adds the project to the create cluster token params
func (o *CreateClusterTokenParams) WithProject(project string) *CreateClusterTokenParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the create cluster token params
func (o *CreateClusterTokenParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *CreateClusterTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param cluster
	if err := r.SetPathParam("cluster", o.Cluster); err != nil {
		return err
	}

	// path param org
	if err := r.SetPathParam("org", o.Org); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
