// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteClusterNodeReader is a Reader for the DeleteClusterNode structure.
type DeleteClusterNodeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteClusterNodeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteClusterNodeNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteClusterNodeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteClusterNodeForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteClusterNodeNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteClusterNodeNoContent creates a DeleteClusterNodeNoContent with default headers values
func NewDeleteClusterNodeNoContent() *DeleteClusterNodeNoContent {
	return &DeleteClusterNodeNoContent{}
}

/*DeleteClusterNodeNoContent handles this case with default header values.

OK
*/
type DeleteClusterNodeNoContent struct {
}

func (o *DeleteClusterNodeNoContent) Error() string {
	return fmt.Sprintf("[DELETE /orgs/{org}/projects/{project}/clusters/{cluster}/node-pools/{node_pool}/nodes/{node}][%d] deleteClusterNodeNoContent ", 204)
}

func (o *DeleteClusterNodeNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteClusterNodeBadRequest creates a DeleteClusterNodeBadRequest with default headers values
func NewDeleteClusterNodeBadRequest() *DeleteClusterNodeBadRequest {
	return &DeleteClusterNodeBadRequest{}
}

/*DeleteClusterNodeBadRequest handles this case with default header values.

Invalid request parameters
*/
type DeleteClusterNodeBadRequest struct {
	Payload string
}

func (o *DeleteClusterNodeBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /orgs/{org}/projects/{project}/clusters/{cluster}/node-pools/{node_pool}/nodes/{node}][%d] deleteClusterNodeBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteClusterNodeBadRequest) GetPayload() string {
	return o.Payload
}

func (o *DeleteClusterNodeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteClusterNodeForbidden creates a DeleteClusterNodeForbidden with default headers values
func NewDeleteClusterNodeForbidden() *DeleteClusterNodeForbidden {
	return &DeleteClusterNodeForbidden{}
}

/*DeleteClusterNodeForbidden handles this case with default header values.

Forbidden
*/
type DeleteClusterNodeForbidden struct {
	Payload string
}

func (o *DeleteClusterNodeForbidden) Error() string {
	return fmt.Sprintf("[DELETE /orgs/{org}/projects/{project}/clusters/{cluster}/node-pools/{node_pool}/nodes/{node}][%d] deleteClusterNodeForbidden  %+v", 403, o.Payload)
}

func (o *DeleteClusterNodeForbidden) GetPayload() string {
	return o.Payload
}

func (o *DeleteClusterNodeForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteClusterNodeNotFound creates a DeleteClusterNodeNotFound with default headers values
func NewDeleteClusterNodeNotFound() *DeleteClusterNodeNotFound {
	return &DeleteClusterNodeNotFound{}
}

/*DeleteClusterNodeNotFound handles this case with default header values.

Resource not found
*/
type DeleteClusterNodeNotFound struct {
	Payload string
}

func (o *DeleteClusterNodeNotFound) Error() string {
	return fmt.Sprintf("[DELETE /orgs/{org}/projects/{project}/clusters/{cluster}/node-pools/{node_pool}/nodes/{node}][%d] deleteClusterNodeNotFound  %+v", 404, o.Payload)
}

func (o *DeleteClusterNodeNotFound) GetPayload() string {
	return o.Payload
}

func (o *DeleteClusterNodeNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
