// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteClusterNodeParams creates a new DeleteClusterNodeParams object
// with the default values initialized.
func NewDeleteClusterNodeParams() *DeleteClusterNodeParams {
	var ()
	return &DeleteClusterNodeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteClusterNodeParamsWithTimeout creates a new DeleteClusterNodeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteClusterNodeParamsWithTimeout(timeout time.Duration) *DeleteClusterNodeParams {
	var ()
	return &DeleteClusterNodeParams{

		timeout: timeout,
	}
}

// NewDeleteClusterNodeParamsWithContext creates a new DeleteClusterNodeParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteClusterNodeParamsWithContext(ctx context.Context) *DeleteClusterNodeParams {
	var ()
	return &DeleteClusterNodeParams{

		Context: ctx,
	}
}

// NewDeleteClusterNodeParamsWithHTTPClient creates a new DeleteClusterNodeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteClusterNodeParamsWithHTTPClient(client *http.Client) *DeleteClusterNodeParams {
	var ()
	return &DeleteClusterNodeParams{
		HTTPClient: client,
	}
}

/*DeleteClusterNodeParams contains all the parameters to send to the API endpoint
for the delete cluster node operation typically these are written to a http.Request
*/
type DeleteClusterNodeParams struct {

	/*Cluster
	  The identifier of a cluster.

	*/
	Cluster string
	/*Node
	  The unique identifier of a worker node in a cluster

	*/
	Node string
	/*NodePool
	  The identifier of a node pool.

	*/
	NodePool string
	/*Org
	  The organization identifier

	*/
	Org string
	/*Project
	  The project identifier

	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete cluster node params
func (o *DeleteClusterNodeParams) WithTimeout(timeout time.Duration) *DeleteClusterNodeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete cluster node params
func (o *DeleteClusterNodeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete cluster node params
func (o *DeleteClusterNodeParams) WithContext(ctx context.Context) *DeleteClusterNodeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete cluster node params
func (o *DeleteClusterNodeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete cluster node params
func (o *DeleteClusterNodeParams) WithHTTPClient(client *http.Client) *DeleteClusterNodeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete cluster node params
func (o *DeleteClusterNodeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCluster adds the cluster to the delete cluster node params
func (o *DeleteClusterNodeParams) WithCluster(cluster string) *DeleteClusterNodeParams {
	o.SetCluster(cluster)
	return o
}

// SetCluster adds the cluster to the delete cluster node params
func (o *DeleteClusterNodeParams) SetCluster(cluster string) {
	o.Cluster = cluster
}

// WithNode adds the node to the delete cluster node params
func (o *DeleteClusterNodeParams) WithNode(node string) *DeleteClusterNodeParams {
	o.SetNode(node)
	return o
}

// SetNode adds the node to the delete cluster node params
func (o *DeleteClusterNodeParams) SetNode(node string) {
	o.Node = node
}

// WithNodePool adds the nodePool to the delete cluster node params
func (o *DeleteClusterNodeParams) WithNodePool(nodePool string) *DeleteClusterNodeParams {
	o.SetNodePool(nodePool)
	return o
}

// SetNodePool adds the nodePool to the delete cluster node params
func (o *DeleteClusterNodeParams) SetNodePool(nodePool string) {
	o.NodePool = nodePool
}

// WithOrg adds the org to the delete cluster node params
func (o *DeleteClusterNodeParams) WithOrg(org string) *DeleteClusterNodeParams {
	o.SetOrg(org)
	return o
}

// SetOrg adds the org to the delete cluster node params
func (o *DeleteClusterNodeParams) SetOrg(org string) {
	o.Org = org
}

// WithProject adds the project to the delete cluster node params
func (o *DeleteClusterNodeParams) WithProject(project string) *DeleteClusterNodeParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the delete cluster node params
func (o *DeleteClusterNodeParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteClusterNodeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster
	if err := r.SetPathParam("cluster", o.Cluster); err != nil {
		return err
	}

	// path param node
	if err := r.SetPathParam("node", o.Node); err != nil {
		return err
	}

	// path param node_pool
	if err := r.SetPathParam("node_pool", o.NodePool); err != nil {
		return err
	}

	// path param org
	if err := r.SetPathParam("org", o.Org); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
