// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteClusterTokenParams creates a new DeleteClusterTokenParams object
// with the default values initialized.
func NewDeleteClusterTokenParams() *DeleteClusterTokenParams {
	var ()
	return &DeleteClusterTokenParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteClusterTokenParamsWithTimeout creates a new DeleteClusterTokenParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteClusterTokenParamsWithTimeout(timeout time.Duration) *DeleteClusterTokenParams {
	var ()
	return &DeleteClusterTokenParams{

		timeout: timeout,
	}
}

// NewDeleteClusterTokenParamsWithContext creates a new DeleteClusterTokenParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteClusterTokenParamsWithContext(ctx context.Context) *DeleteClusterTokenParams {
	var ()
	return &DeleteClusterTokenParams{

		Context: ctx,
	}
}

// NewDeleteClusterTokenParamsWithHTTPClient creates a new DeleteClusterTokenParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteClusterTokenParamsWithHTTPClient(client *http.Client) *DeleteClusterTokenParams {
	var ()
	return &DeleteClusterTokenParams{
		HTTPClient: client,
	}
}

/*DeleteClusterTokenParams contains all the parameters to send to the API endpoint
for the delete cluster token operation typically these are written to a http.Request
*/
type DeleteClusterTokenParams struct {

	/*Cluster
	  The identifier of a cluster.

	*/
	Cluster string
	/*Org
	  The organization identifier

	*/
	Org string
	/*Project
	  The project identifier

	*/
	Project string
	/*Token
	  The token of Kubernetes cluster

	*/
	Token string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete cluster token params
func (o *DeleteClusterTokenParams) WithTimeout(timeout time.Duration) *DeleteClusterTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete cluster token params
func (o *DeleteClusterTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete cluster token params
func (o *DeleteClusterTokenParams) WithContext(ctx context.Context) *DeleteClusterTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete cluster token params
func (o *DeleteClusterTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete cluster token params
func (o *DeleteClusterTokenParams) WithHTTPClient(client *http.Client) *DeleteClusterTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete cluster token params
func (o *DeleteClusterTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCluster adds the cluster to the delete cluster token params
func (o *DeleteClusterTokenParams) WithCluster(cluster string) *DeleteClusterTokenParams {
	o.SetCluster(cluster)
	return o
}

// SetCluster adds the cluster to the delete cluster token params
func (o *DeleteClusterTokenParams) SetCluster(cluster string) {
	o.Cluster = cluster
}

// WithOrg adds the org to the delete cluster token params
func (o *DeleteClusterTokenParams) WithOrg(org string) *DeleteClusterTokenParams {
	o.SetOrg(org)
	return o
}

// SetOrg adds the org to the delete cluster token params
func (o *DeleteClusterTokenParams) SetOrg(org string) {
	o.Org = org
}

// WithProject adds the project to the delete cluster token params
func (o *DeleteClusterTokenParams) WithProject(project string) *DeleteClusterTokenParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the delete cluster token params
func (o *DeleteClusterTokenParams) SetProject(project string) {
	o.Project = project
}

// WithToken adds the token to the delete cluster token params
func (o *DeleteClusterTokenParams) WithToken(token string) *DeleteClusterTokenParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the delete cluster token params
func (o *DeleteClusterTokenParams) SetToken(token string) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteClusterTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster
	if err := r.SetPathParam("cluster", o.Cluster); err != nil {
		return err
	}

	// path param org
	if err := r.SetPathParam("org", o.Org); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	// path param token
	if err := r.SetPathParam("token", o.Token); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
