// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteClusterParams creates a new DeleteClusterParams object
// with the default values initialized.
func NewDeleteClusterParams() *DeleteClusterParams {
	var ()
	return &DeleteClusterParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteClusterParamsWithTimeout creates a new DeleteClusterParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteClusterParamsWithTimeout(timeout time.Duration) *DeleteClusterParams {
	var ()
	return &DeleteClusterParams{

		timeout: timeout,
	}
}

// NewDeleteClusterParamsWithContext creates a new DeleteClusterParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteClusterParamsWithContext(ctx context.Context) *DeleteClusterParams {
	var ()
	return &DeleteClusterParams{

		Context: ctx,
	}
}

// NewDeleteClusterParamsWithHTTPClient creates a new DeleteClusterParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteClusterParamsWithHTTPClient(client *http.Client) *DeleteClusterParams {
	var ()
	return &DeleteClusterParams{
		HTTPClient: client,
	}
}

/*DeleteClusterParams contains all the parameters to send to the API endpoint
for the delete cluster operation typically these are written to a http.Request
*/
type DeleteClusterParams struct {

	/*Cluster
	  The identifier of a cluster

	*/
	Cluster string
	/*Org
	  The organization identifier

	*/
	Org string
	/*Project
	  The project identifier

	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete cluster params
func (o *DeleteClusterParams) WithTimeout(timeout time.Duration) *DeleteClusterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete cluster params
func (o *DeleteClusterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete cluster params
func (o *DeleteClusterParams) WithContext(ctx context.Context) *DeleteClusterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete cluster params
func (o *DeleteClusterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete cluster params
func (o *DeleteClusterParams) WithHTTPClient(client *http.Client) *DeleteClusterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete cluster params
func (o *DeleteClusterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCluster adds the cluster to the delete cluster params
func (o *DeleteClusterParams) WithCluster(cluster string) *DeleteClusterParams {
	o.SetCluster(cluster)
	return o
}

// SetCluster adds the cluster to the delete cluster params
func (o *DeleteClusterParams) SetCluster(cluster string) {
	o.Cluster = cluster
}

// WithOrg adds the org to the delete cluster params
func (o *DeleteClusterParams) WithOrg(org string) *DeleteClusterParams {
	o.SetOrg(org)
	return o
}

// SetOrg adds the org to the delete cluster params
func (o *DeleteClusterParams) SetOrg(org string) {
	o.Org = org
}

// WithProject adds the project to the delete cluster params
func (o *DeleteClusterParams) WithProject(project string) *DeleteClusterParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the delete cluster params
func (o *DeleteClusterParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteClusterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster
	if err := r.SetPathParam("cluster", o.Cluster); err != nil {
		return err
	}

	// path param org
	if err := r.SetPathParam("org", o.Org); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
