// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteClusterTokenReader is a Reader for the DeleteClusterToken structure.
type DeleteClusterTokenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteClusterTokenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteClusterTokenNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteClusterTokenBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteClusterTokenForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteClusterTokenNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteClusterTokenNoContent creates a DeleteClusterTokenNoContent with default headers values
func NewDeleteClusterTokenNoContent() *DeleteClusterTokenNoContent {
	return &DeleteClusterTokenNoContent{}
}

/*DeleteClusterTokenNoContent handles this case with default header values.

OK
*/
type DeleteClusterTokenNoContent struct {
}

func (o *DeleteClusterTokenNoContent) Error() string {
	return fmt.Sprintf("[DELETE /orgs/{org}/projects/{project}/clusters/{cluster}/tokens/{token}][%d] deleteClusterTokenNoContent ", 204)
}

func (o *DeleteClusterTokenNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteClusterTokenBadRequest creates a DeleteClusterTokenBadRequest with default headers values
func NewDeleteClusterTokenBadRequest() *DeleteClusterTokenBadRequest {
	return &DeleteClusterTokenBadRequest{}
}

/*DeleteClusterTokenBadRequest handles this case with default header values.

Invalid request parameters
*/
type DeleteClusterTokenBadRequest struct {
	Payload string
}

func (o *DeleteClusterTokenBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /orgs/{org}/projects/{project}/clusters/{cluster}/tokens/{token}][%d] deleteClusterTokenBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteClusterTokenBadRequest) GetPayload() string {
	return o.Payload
}

func (o *DeleteClusterTokenBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteClusterTokenForbidden creates a DeleteClusterTokenForbidden with default headers values
func NewDeleteClusterTokenForbidden() *DeleteClusterTokenForbidden {
	return &DeleteClusterTokenForbidden{}
}

/*DeleteClusterTokenForbidden handles this case with default header values.

Forbidden
*/
type DeleteClusterTokenForbidden struct {
	Payload string
}

func (o *DeleteClusterTokenForbidden) Error() string {
	return fmt.Sprintf("[DELETE /orgs/{org}/projects/{project}/clusters/{cluster}/tokens/{token}][%d] deleteClusterTokenForbidden  %+v", 403, o.Payload)
}

func (o *DeleteClusterTokenForbidden) GetPayload() string {
	return o.Payload
}

func (o *DeleteClusterTokenForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteClusterTokenNotFound creates a DeleteClusterTokenNotFound with default headers values
func NewDeleteClusterTokenNotFound() *DeleteClusterTokenNotFound {
	return &DeleteClusterTokenNotFound{}
}

/*DeleteClusterTokenNotFound handles this case with default header values.

Resource not found
*/
type DeleteClusterTokenNotFound struct {
	Payload string
}

func (o *DeleteClusterTokenNotFound) Error() string {
	return fmt.Sprintf("[DELETE /orgs/{org}/projects/{project}/clusters/{cluster}/tokens/{token}][%d] deleteClusterTokenNotFound  %+v", 404, o.Payload)
}

func (o *DeleteClusterTokenNotFound) GetPayload() string {
	return o.Payload
}

func (o *DeleteClusterTokenNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
