// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/EricomSoftwareLtd/ridge-go/models"
)

// DescribeClusterNodePoolReader is a Reader for the DescribeClusterNodePool structure.
type DescribeClusterNodePoolReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DescribeClusterNodePoolReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDescribeClusterNodePoolOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDescribeClusterNodePoolBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDescribeClusterNodePoolForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDescribeClusterNodePoolNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDescribeClusterNodePoolOK creates a DescribeClusterNodePoolOK with default headers values
func NewDescribeClusterNodePoolOK() *DescribeClusterNodePoolOK {
	return &DescribeClusterNodePoolOK{}
}

/*DescribeClusterNodePoolOK handles this case with default header values.

OK
*/
type DescribeClusterNodePoolOK struct {
	Payload *models.NodePool
}

func (o *DescribeClusterNodePoolOK) Error() string {
	return fmt.Sprintf("[GET /orgs/{org}/projects/{project}/clusters/{cluster}/node-pools/{node_pool}][%d] describeClusterNodePoolOK  %+v", 200, o.Payload)
}

func (o *DescribeClusterNodePoolOK) GetPayload() *models.NodePool {
	return o.Payload
}

func (o *DescribeClusterNodePoolOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NodePool)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDescribeClusterNodePoolBadRequest creates a DescribeClusterNodePoolBadRequest with default headers values
func NewDescribeClusterNodePoolBadRequest() *DescribeClusterNodePoolBadRequest {
	return &DescribeClusterNodePoolBadRequest{}
}

/*DescribeClusterNodePoolBadRequest handles this case with default header values.

Invalid request parameters
*/
type DescribeClusterNodePoolBadRequest struct {
	Payload string
}

func (o *DescribeClusterNodePoolBadRequest) Error() string {
	return fmt.Sprintf("[GET /orgs/{org}/projects/{project}/clusters/{cluster}/node-pools/{node_pool}][%d] describeClusterNodePoolBadRequest  %+v", 400, o.Payload)
}

func (o *DescribeClusterNodePoolBadRequest) GetPayload() string {
	return o.Payload
}

func (o *DescribeClusterNodePoolBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDescribeClusterNodePoolForbidden creates a DescribeClusterNodePoolForbidden with default headers values
func NewDescribeClusterNodePoolForbidden() *DescribeClusterNodePoolForbidden {
	return &DescribeClusterNodePoolForbidden{}
}

/*DescribeClusterNodePoolForbidden handles this case with default header values.

Forbidden
*/
type DescribeClusterNodePoolForbidden struct {
	Payload string
}

func (o *DescribeClusterNodePoolForbidden) Error() string {
	return fmt.Sprintf("[GET /orgs/{org}/projects/{project}/clusters/{cluster}/node-pools/{node_pool}][%d] describeClusterNodePoolForbidden  %+v", 403, o.Payload)
}

func (o *DescribeClusterNodePoolForbidden) GetPayload() string {
	return o.Payload
}

func (o *DescribeClusterNodePoolForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDescribeClusterNodePoolNotFound creates a DescribeClusterNodePoolNotFound with default headers values
func NewDescribeClusterNodePoolNotFound() *DescribeClusterNodePoolNotFound {
	return &DescribeClusterNodePoolNotFound{}
}

/*DescribeClusterNodePoolNotFound handles this case with default header values.

Resource not found
*/
type DescribeClusterNodePoolNotFound struct {
	Payload string
}

func (o *DescribeClusterNodePoolNotFound) Error() string {
	return fmt.Sprintf("[GET /orgs/{org}/projects/{project}/clusters/{cluster}/node-pools/{node_pool}][%d] describeClusterNodePoolNotFound  %+v", 404, o.Payload)
}

func (o *DescribeClusterNodePoolNotFound) GetPayload() string {
	return o.Payload
}

func (o *DescribeClusterNodePoolNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
