// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/EricomSoftwareLtd/ridge-go/models"
)

// DescribeClusterNodeReader is a Reader for the DescribeClusterNode structure.
type DescribeClusterNodeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DescribeClusterNodeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDescribeClusterNodeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDescribeClusterNodeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDescribeClusterNodeForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDescribeClusterNodeNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDescribeClusterNodeOK creates a DescribeClusterNodeOK with default headers values
func NewDescribeClusterNodeOK() *DescribeClusterNodeOK {
	return &DescribeClusterNodeOK{}
}

/*DescribeClusterNodeOK handles this case with default header values.

OK
*/
type DescribeClusterNodeOK struct {
	Payload *models.Node
}

func (o *DescribeClusterNodeOK) Error() string {
	return fmt.Sprintf("[GET /orgs/{org}/projects/{project}/clusters/{cluster}/node-pools/{node_pool}/nodes/{node}][%d] describeClusterNodeOK  %+v", 200, o.Payload)
}

func (o *DescribeClusterNodeOK) GetPayload() *models.Node {
	return o.Payload
}

func (o *DescribeClusterNodeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Node)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDescribeClusterNodeBadRequest creates a DescribeClusterNodeBadRequest with default headers values
func NewDescribeClusterNodeBadRequest() *DescribeClusterNodeBadRequest {
	return &DescribeClusterNodeBadRequest{}
}

/*DescribeClusterNodeBadRequest handles this case with default header values.

Invalid request parameters
*/
type DescribeClusterNodeBadRequest struct {
	Payload string
}

func (o *DescribeClusterNodeBadRequest) Error() string {
	return fmt.Sprintf("[GET /orgs/{org}/projects/{project}/clusters/{cluster}/node-pools/{node_pool}/nodes/{node}][%d] describeClusterNodeBadRequest  %+v", 400, o.Payload)
}

func (o *DescribeClusterNodeBadRequest) GetPayload() string {
	return o.Payload
}

func (o *DescribeClusterNodeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDescribeClusterNodeForbidden creates a DescribeClusterNodeForbidden with default headers values
func NewDescribeClusterNodeForbidden() *DescribeClusterNodeForbidden {
	return &DescribeClusterNodeForbidden{}
}

/*DescribeClusterNodeForbidden handles this case with default header values.

Forbidden
*/
type DescribeClusterNodeForbidden struct {
	Payload string
}

func (o *DescribeClusterNodeForbidden) Error() string {
	return fmt.Sprintf("[GET /orgs/{org}/projects/{project}/clusters/{cluster}/node-pools/{node_pool}/nodes/{node}][%d] describeClusterNodeForbidden  %+v", 403, o.Payload)
}

func (o *DescribeClusterNodeForbidden) GetPayload() string {
	return o.Payload
}

func (o *DescribeClusterNodeForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDescribeClusterNodeNotFound creates a DescribeClusterNodeNotFound with default headers values
func NewDescribeClusterNodeNotFound() *DescribeClusterNodeNotFound {
	return &DescribeClusterNodeNotFound{}
}

/*DescribeClusterNodeNotFound handles this case with default header values.

Resource not found
*/
type DescribeClusterNodeNotFound struct {
	Payload string
}

func (o *DescribeClusterNodeNotFound) Error() string {
	return fmt.Sprintf("[GET /orgs/{org}/projects/{project}/clusters/{cluster}/node-pools/{node_pool}/nodes/{node}][%d] describeClusterNodeNotFound  %+v", 404, o.Payload)
}

func (o *DescribeClusterNodeNotFound) GetPayload() string {
	return o.Payload
}

func (o *DescribeClusterNodeNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
