// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/EricomSoftwareLtd/ridge-go/models"
)

// DescribeClusterReader is a Reader for the DescribeCluster structure.
type DescribeClusterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DescribeClusterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDescribeClusterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDescribeClusterBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDescribeClusterForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDescribeClusterNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDescribeClusterOK creates a DescribeClusterOK with default headers values
func NewDescribeClusterOK() *DescribeClusterOK {
	return &DescribeClusterOK{}
}

/*DescribeClusterOK handles this case with default header values.

Success
*/
type DescribeClusterOK struct {
	Payload *models.Cluster
}

func (o *DescribeClusterOK) Error() string {
	return fmt.Sprintf("[GET /orgs/{org}/projects/{project}/clusters/{cluster}][%d] describeClusterOK  %+v", 200, o.Payload)
}

func (o *DescribeClusterOK) GetPayload() *models.Cluster {
	return o.Payload
}

func (o *DescribeClusterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Cluster)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDescribeClusterBadRequest creates a DescribeClusterBadRequest with default headers values
func NewDescribeClusterBadRequest() *DescribeClusterBadRequest {
	return &DescribeClusterBadRequest{}
}

/*DescribeClusterBadRequest handles this case with default header values.

Invalid request parameters
*/
type DescribeClusterBadRequest struct {
	Payload string
}

func (o *DescribeClusterBadRequest) Error() string {
	return fmt.Sprintf("[GET /orgs/{org}/projects/{project}/clusters/{cluster}][%d] describeClusterBadRequest  %+v", 400, o.Payload)
}

func (o *DescribeClusterBadRequest) GetPayload() string {
	return o.Payload
}

func (o *DescribeClusterBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDescribeClusterForbidden creates a DescribeClusterForbidden with default headers values
func NewDescribeClusterForbidden() *DescribeClusterForbidden {
	return &DescribeClusterForbidden{}
}

/*DescribeClusterForbidden handles this case with default header values.

Forbidden
*/
type DescribeClusterForbidden struct {
	Payload string
}

func (o *DescribeClusterForbidden) Error() string {
	return fmt.Sprintf("[GET /orgs/{org}/projects/{project}/clusters/{cluster}][%d] describeClusterForbidden  %+v", 403, o.Payload)
}

func (o *DescribeClusterForbidden) GetPayload() string {
	return o.Payload
}

func (o *DescribeClusterForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDescribeClusterNotFound creates a DescribeClusterNotFound with default headers values
func NewDescribeClusterNotFound() *DescribeClusterNotFound {
	return &DescribeClusterNotFound{}
}

/*DescribeClusterNotFound handles this case with default header values.

Resource not found
*/
type DescribeClusterNotFound struct {
	Payload string
}

func (o *DescribeClusterNotFound) Error() string {
	return fmt.Sprintf("[GET /orgs/{org}/projects/{project}/clusters/{cluster}][%d] describeClusterNotFound  %+v", 404, o.Payload)
}

func (o *DescribeClusterNotFound) GetPayload() string {
	return o.Payload
}

func (o *DescribeClusterNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
