// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDescribeClusterTokenParams creates a new DescribeClusterTokenParams object
// with the default values initialized.
func NewDescribeClusterTokenParams() *DescribeClusterTokenParams {
	var ()
	return &DescribeClusterTokenParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDescribeClusterTokenParamsWithTimeout creates a new DescribeClusterTokenParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDescribeClusterTokenParamsWithTimeout(timeout time.Duration) *DescribeClusterTokenParams {
	var ()
	return &DescribeClusterTokenParams{

		timeout: timeout,
	}
}

// NewDescribeClusterTokenParamsWithContext creates a new DescribeClusterTokenParams object
// with the default values initialized, and the ability to set a context for a request
func NewDescribeClusterTokenParamsWithContext(ctx context.Context) *DescribeClusterTokenParams {
	var ()
	return &DescribeClusterTokenParams{

		Context: ctx,
	}
}

// NewDescribeClusterTokenParamsWithHTTPClient creates a new DescribeClusterTokenParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDescribeClusterTokenParamsWithHTTPClient(client *http.Client) *DescribeClusterTokenParams {
	var ()
	return &DescribeClusterTokenParams{
		HTTPClient: client,
	}
}

/*DescribeClusterTokenParams contains all the parameters to send to the API endpoint
for the describe cluster token operation typically these are written to a http.Request
*/
type DescribeClusterTokenParams struct {

	/*Cluster
	  The identifier of a cluster.

	*/
	Cluster string
	/*Org
	  The organization identifier

	*/
	Org string
	/*Project
	  The project identifier

	*/
	Project string
	/*Token
	  The token of Kubernetes cluster

	*/
	Token string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the describe cluster token params
func (o *DescribeClusterTokenParams) WithTimeout(timeout time.Duration) *DescribeClusterTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the describe cluster token params
func (o *DescribeClusterTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the describe cluster token params
func (o *DescribeClusterTokenParams) WithContext(ctx context.Context) *DescribeClusterTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the describe cluster token params
func (o *DescribeClusterTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the describe cluster token params
func (o *DescribeClusterTokenParams) WithHTTPClient(client *http.Client) *DescribeClusterTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the describe cluster token params
func (o *DescribeClusterTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCluster adds the cluster to the describe cluster token params
func (o *DescribeClusterTokenParams) WithCluster(cluster string) *DescribeClusterTokenParams {
	o.SetCluster(cluster)
	return o
}

// SetCluster adds the cluster to the describe cluster token params
func (o *DescribeClusterTokenParams) SetCluster(cluster string) {
	o.Cluster = cluster
}

// WithOrg adds the org to the describe cluster token params
func (o *DescribeClusterTokenParams) WithOrg(org string) *DescribeClusterTokenParams {
	o.SetOrg(org)
	return o
}

// SetOrg adds the org to the describe cluster token params
func (o *DescribeClusterTokenParams) SetOrg(org string) {
	o.Org = org
}

// WithProject adds the project to the describe cluster token params
func (o *DescribeClusterTokenParams) WithProject(project string) *DescribeClusterTokenParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the describe cluster token params
func (o *DescribeClusterTokenParams) SetProject(project string) {
	o.Project = project
}

// WithToken adds the token to the describe cluster token params
func (o *DescribeClusterTokenParams) WithToken(token string) *DescribeClusterTokenParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the describe cluster token params
func (o *DescribeClusterTokenParams) SetToken(token string) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *DescribeClusterTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster
	if err := r.SetPathParam("cluster", o.Cluster); err != nil {
		return err
	}

	// path param org
	if err := r.SetPathParam("org", o.Org); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	// path param token
	if err := r.SetPathParam("token", o.Token); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
