// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDescribeClusterCaCertificateParams creates a new DescribeClusterCaCertificateParams object
// with the default values initialized.
func NewDescribeClusterCaCertificateParams() *DescribeClusterCaCertificateParams {
	var ()
	return &DescribeClusterCaCertificateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDescribeClusterCaCertificateParamsWithTimeout creates a new DescribeClusterCaCertificateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDescribeClusterCaCertificateParamsWithTimeout(timeout time.Duration) *DescribeClusterCaCertificateParams {
	var ()
	return &DescribeClusterCaCertificateParams{

		timeout: timeout,
	}
}

// NewDescribeClusterCaCertificateParamsWithContext creates a new DescribeClusterCaCertificateParams object
// with the default values initialized, and the ability to set a context for a request
func NewDescribeClusterCaCertificateParamsWithContext(ctx context.Context) *DescribeClusterCaCertificateParams {
	var ()
	return &DescribeClusterCaCertificateParams{

		Context: ctx,
	}
}

// NewDescribeClusterCaCertificateParamsWithHTTPClient creates a new DescribeClusterCaCertificateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDescribeClusterCaCertificateParamsWithHTTPClient(client *http.Client) *DescribeClusterCaCertificateParams {
	var ()
	return &DescribeClusterCaCertificateParams{
		HTTPClient: client,
	}
}

/*DescribeClusterCaCertificateParams contains all the parameters to send to the API endpoint
for the describe cluster ca certificate operation typically these are written to a http.Request
*/
type DescribeClusterCaCertificateParams struct {

	/*Cluster
	  The identifier of a cluster

	*/
	Cluster string
	/*Org
	  The organization identifier

	*/
	Org string
	/*Project
	  The project identifier

	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the describe cluster ca certificate params
func (o *DescribeClusterCaCertificateParams) WithTimeout(timeout time.Duration) *DescribeClusterCaCertificateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the describe cluster ca certificate params
func (o *DescribeClusterCaCertificateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the describe cluster ca certificate params
func (o *DescribeClusterCaCertificateParams) WithContext(ctx context.Context) *DescribeClusterCaCertificateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the describe cluster ca certificate params
func (o *DescribeClusterCaCertificateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the describe cluster ca certificate params
func (o *DescribeClusterCaCertificateParams) WithHTTPClient(client *http.Client) *DescribeClusterCaCertificateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the describe cluster ca certificate params
func (o *DescribeClusterCaCertificateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCluster adds the cluster to the describe cluster ca certificate params
func (o *DescribeClusterCaCertificateParams) WithCluster(cluster string) *DescribeClusterCaCertificateParams {
	o.SetCluster(cluster)
	return o
}

// SetCluster adds the cluster to the describe cluster ca certificate params
func (o *DescribeClusterCaCertificateParams) SetCluster(cluster string) {
	o.Cluster = cluster
}

// WithOrg adds the org to the describe cluster ca certificate params
func (o *DescribeClusterCaCertificateParams) WithOrg(org string) *DescribeClusterCaCertificateParams {
	o.SetOrg(org)
	return o
}

// SetOrg adds the org to the describe cluster ca certificate params
func (o *DescribeClusterCaCertificateParams) SetOrg(org string) {
	o.Org = org
}

// WithProject adds the project to the describe cluster ca certificate params
func (o *DescribeClusterCaCertificateParams) WithProject(project string) *DescribeClusterCaCertificateParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the describe cluster ca certificate params
func (o *DescribeClusterCaCertificateParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *DescribeClusterCaCertificateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster
	if err := r.SetPathParam("cluster", o.Cluster); err != nil {
		return err
	}

	// path param org
	if err := r.SetPathParam("org", o.Org); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
