// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDescribeClusterNodePoolParams creates a new DescribeClusterNodePoolParams object
// with the default values initialized.
func NewDescribeClusterNodePoolParams() *DescribeClusterNodePoolParams {
	var ()
	return &DescribeClusterNodePoolParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDescribeClusterNodePoolParamsWithTimeout creates a new DescribeClusterNodePoolParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDescribeClusterNodePoolParamsWithTimeout(timeout time.Duration) *DescribeClusterNodePoolParams {
	var ()
	return &DescribeClusterNodePoolParams{

		timeout: timeout,
	}
}

// NewDescribeClusterNodePoolParamsWithContext creates a new DescribeClusterNodePoolParams object
// with the default values initialized, and the ability to set a context for a request
func NewDescribeClusterNodePoolParamsWithContext(ctx context.Context) *DescribeClusterNodePoolParams {
	var ()
	return &DescribeClusterNodePoolParams{

		Context: ctx,
	}
}

// NewDescribeClusterNodePoolParamsWithHTTPClient creates a new DescribeClusterNodePoolParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDescribeClusterNodePoolParamsWithHTTPClient(client *http.Client) *DescribeClusterNodePoolParams {
	var ()
	return &DescribeClusterNodePoolParams{
		HTTPClient: client,
	}
}

/*DescribeClusterNodePoolParams contains all the parameters to send to the API endpoint
for the describe cluster node pool operation typically these are written to a http.Request
*/
type DescribeClusterNodePoolParams struct {

	/*Cluster
	  The identifier of a cluster.

	*/
	Cluster string
	/*NodePool
	  The identifier of a node pool in a cluster

	*/
	NodePool string
	/*Org
	  The organization identifier

	*/
	Org string
	/*Project
	  The project identifier

	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the describe cluster node pool params
func (o *DescribeClusterNodePoolParams) WithTimeout(timeout time.Duration) *DescribeClusterNodePoolParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the describe cluster node pool params
func (o *DescribeClusterNodePoolParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the describe cluster node pool params
func (o *DescribeClusterNodePoolParams) WithContext(ctx context.Context) *DescribeClusterNodePoolParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the describe cluster node pool params
func (o *DescribeClusterNodePoolParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the describe cluster node pool params
func (o *DescribeClusterNodePoolParams) WithHTTPClient(client *http.Client) *DescribeClusterNodePoolParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the describe cluster node pool params
func (o *DescribeClusterNodePoolParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCluster adds the cluster to the describe cluster node pool params
func (o *DescribeClusterNodePoolParams) WithCluster(cluster string) *DescribeClusterNodePoolParams {
	o.SetCluster(cluster)
	return o
}

// SetCluster adds the cluster to the describe cluster node pool params
func (o *DescribeClusterNodePoolParams) SetCluster(cluster string) {
	o.Cluster = cluster
}

// WithNodePool adds the nodePool to the describe cluster node pool params
func (o *DescribeClusterNodePoolParams) WithNodePool(nodePool string) *DescribeClusterNodePoolParams {
	o.SetNodePool(nodePool)
	return o
}

// SetNodePool adds the nodePool to the describe cluster node pool params
func (o *DescribeClusterNodePoolParams) SetNodePool(nodePool string) {
	o.NodePool = nodePool
}

// WithOrg adds the org to the describe cluster node pool params
func (o *DescribeClusterNodePoolParams) WithOrg(org string) *DescribeClusterNodePoolParams {
	o.SetOrg(org)
	return o
}

// SetOrg adds the org to the describe cluster node pool params
func (o *DescribeClusterNodePoolParams) SetOrg(org string) {
	o.Org = org
}

// WithProject adds the project to the describe cluster node pool params
func (o *DescribeClusterNodePoolParams) WithProject(project string) *DescribeClusterNodePoolParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the describe cluster node pool params
func (o *DescribeClusterNodePoolParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *DescribeClusterNodePoolParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster
	if err := r.SetPathParam("cluster", o.Cluster); err != nil {
		return err
	}

	// path param node_pool
	if err := r.SetPathParam("node_pool", o.NodePool); err != nil {
		return err
	}

	// path param org
	if err := r.SetPathParam("org", o.Org); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
