// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/EricomSoftwareLtd/ridge-go/models"
)

// ListNodePresetsReader is a Reader for the ListNodePresets structure.
type ListNodePresetsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListNodePresetsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListNodePresetsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListNodePresetsOK creates a ListNodePresetsOK with default headers values
func NewListNodePresetsOK() *ListNodePresetsOK {
	return &ListNodePresetsOK{}
}

/*ListNodePresetsOK handles this case with default header values.

Success
*/
type ListNodePresetsOK struct {
	Payload *models.NodePresets
}

func (o *ListNodePresetsOK) Error() string {
	return fmt.Sprintf("[GET /node-presets][%d] listNodePresetsOK  %+v", 200, o.Payload)
}

func (o *ListNodePresetsOK) GetPayload() *models.NodePresets {
	return o.Payload
}

func (o *ListNodePresetsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NodePresets)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
