// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListClusterNodePoolsParams creates a new ListClusterNodePoolsParams object
// with the default values initialized.
func NewListClusterNodePoolsParams() *ListClusterNodePoolsParams {
	var ()
	return &ListClusterNodePoolsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListClusterNodePoolsParamsWithTimeout creates a new ListClusterNodePoolsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListClusterNodePoolsParamsWithTimeout(timeout time.Duration) *ListClusterNodePoolsParams {
	var ()
	return &ListClusterNodePoolsParams{

		timeout: timeout,
	}
}

// NewListClusterNodePoolsParamsWithContext creates a new ListClusterNodePoolsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListClusterNodePoolsParamsWithContext(ctx context.Context) *ListClusterNodePoolsParams {
	var ()
	return &ListClusterNodePoolsParams{

		Context: ctx,
	}
}

// NewListClusterNodePoolsParamsWithHTTPClient creates a new ListClusterNodePoolsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListClusterNodePoolsParamsWithHTTPClient(client *http.Client) *ListClusterNodePoolsParams {
	var ()
	return &ListClusterNodePoolsParams{
		HTTPClient: client,
	}
}

/*ListClusterNodePoolsParams contains all the parameters to send to the API endpoint
for the list cluster node pools operation typically these are written to a http.Request
*/
type ListClusterNodePoolsParams struct {

	/*Cluster
	  The identifier of a cluster.

	*/
	Cluster string
	/*Org
	  The organization identifier

	*/
	Org string
	/*Project
	  The project identifier

	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list cluster node pools params
func (o *ListClusterNodePoolsParams) WithTimeout(timeout time.Duration) *ListClusterNodePoolsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list cluster node pools params
func (o *ListClusterNodePoolsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list cluster node pools params
func (o *ListClusterNodePoolsParams) WithContext(ctx context.Context) *ListClusterNodePoolsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list cluster node pools params
func (o *ListClusterNodePoolsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list cluster node pools params
func (o *ListClusterNodePoolsParams) WithHTTPClient(client *http.Client) *ListClusterNodePoolsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list cluster node pools params
func (o *ListClusterNodePoolsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCluster adds the cluster to the list cluster node pools params
func (o *ListClusterNodePoolsParams) WithCluster(cluster string) *ListClusterNodePoolsParams {
	o.SetCluster(cluster)
	return o
}

// SetCluster adds the cluster to the list cluster node pools params
func (o *ListClusterNodePoolsParams) SetCluster(cluster string) {
	o.Cluster = cluster
}

// WithOrg adds the org to the list cluster node pools params
func (o *ListClusterNodePoolsParams) WithOrg(org string) *ListClusterNodePoolsParams {
	o.SetOrg(org)
	return o
}

// SetOrg adds the org to the list cluster node pools params
func (o *ListClusterNodePoolsParams) SetOrg(org string) {
	o.Org = org
}

// WithProject adds the project to the list cluster node pools params
func (o *ListClusterNodePoolsParams) WithProject(project string) *ListClusterNodePoolsParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the list cluster node pools params
func (o *ListClusterNodePoolsParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *ListClusterNodePoolsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster
	if err := r.SetPathParam("cluster", o.Cluster); err != nil {
		return err
	}

	// path param org
	if err := r.SetPathParam("org", o.Org); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
