// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/EricomSoftwareLtd/ridge-go/models"
)

// ListClusterLBsReader is a Reader for the ListClusterLBs structure.
type ListClusterLBsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListClusterLBsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListClusterLBsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListClusterLBsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewListClusterLBsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListClusterLBsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListClusterLBsOK creates a ListClusterLBsOK with default headers values
func NewListClusterLBsOK() *ListClusterLBsOK {
	return &ListClusterLBsOK{}
}

/*ListClusterLBsOK handles this case with default header values.

Success
*/
type ListClusterLBsOK struct {
	Payload *models.LoadBalancers
}

func (o *ListClusterLBsOK) Error() string {
	return fmt.Sprintf("[GET /orgs/{org}/projects/{project}/clusters/{cluster}/load-balancers][%d] listClusterLBsOK  %+v", 200, o.Payload)
}

func (o *ListClusterLBsOK) GetPayload() *models.LoadBalancers {
	return o.Payload
}

func (o *ListClusterLBsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LoadBalancers)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListClusterLBsBadRequest creates a ListClusterLBsBadRequest with default headers values
func NewListClusterLBsBadRequest() *ListClusterLBsBadRequest {
	return &ListClusterLBsBadRequest{}
}

/*ListClusterLBsBadRequest handles this case with default header values.

Invalid request parameters
*/
type ListClusterLBsBadRequest struct {
	Payload string
}

func (o *ListClusterLBsBadRequest) Error() string {
	return fmt.Sprintf("[GET /orgs/{org}/projects/{project}/clusters/{cluster}/load-balancers][%d] listClusterLBsBadRequest  %+v", 400, o.Payload)
}

func (o *ListClusterLBsBadRequest) GetPayload() string {
	return o.Payload
}

func (o *ListClusterLBsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListClusterLBsForbidden creates a ListClusterLBsForbidden with default headers values
func NewListClusterLBsForbidden() *ListClusterLBsForbidden {
	return &ListClusterLBsForbidden{}
}

/*ListClusterLBsForbidden handles this case with default header values.

Forbidden
*/
type ListClusterLBsForbidden struct {
	Payload string
}

func (o *ListClusterLBsForbidden) Error() string {
	return fmt.Sprintf("[GET /orgs/{org}/projects/{project}/clusters/{cluster}/load-balancers][%d] listClusterLBsForbidden  %+v", 403, o.Payload)
}

func (o *ListClusterLBsForbidden) GetPayload() string {
	return o.Payload
}

func (o *ListClusterLBsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListClusterLBsNotFound creates a ListClusterLBsNotFound with default headers values
func NewListClusterLBsNotFound() *ListClusterLBsNotFound {
	return &ListClusterLBsNotFound{}
}

/*ListClusterLBsNotFound handles this case with default header values.

Resource not found
*/
type ListClusterLBsNotFound struct {
	Payload string
}

func (o *ListClusterLBsNotFound) Error() string {
	return fmt.Sprintf("[GET /orgs/{org}/projects/{project}/clusters/{cluster}/load-balancers][%d] listClusterLBsNotFound  %+v", 404, o.Payload)
}

func (o *ListClusterLBsNotFound) GetPayload() string {
	return o.Payload
}

func (o *ListClusterLBsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
