// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListClusterNodesParams creates a new ListClusterNodesParams object
// with the default values initialized.
func NewListClusterNodesParams() *ListClusterNodesParams {
	var (
		stateDefault = []string{"starting", "running", "terminating", "terminated"}
	)
	return &ListClusterNodesParams{
		State: stateDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewListClusterNodesParamsWithTimeout creates a new ListClusterNodesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListClusterNodesParamsWithTimeout(timeout time.Duration) *ListClusterNodesParams {
	var (
		stateDefault = []string{"starting", "running", "terminating", "terminated"}
	)
	return &ListClusterNodesParams{
		State: stateDefault,

		timeout: timeout,
	}
}

// NewListClusterNodesParamsWithContext creates a new ListClusterNodesParams object
// with the default values initialized, and the ability to set a context for a request
func NewListClusterNodesParamsWithContext(ctx context.Context) *ListClusterNodesParams {
	var (
		stateDefault = []string{"starting", "running", "terminating", "terminated"}
	)
	return &ListClusterNodesParams{
		State: stateDefault,

		Context: ctx,
	}
}

// NewListClusterNodesParamsWithHTTPClient creates a new ListClusterNodesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListClusterNodesParamsWithHTTPClient(client *http.Client) *ListClusterNodesParams {
	var (
		stateDefault = []string{"starting", "running", "terminating", "terminated"}
	)
	return &ListClusterNodesParams{
		State:      stateDefault,
		HTTPClient: client,
	}
}

/*ListClusterNodesParams contains all the parameters to send to the API endpoint
for the list cluster nodes operation typically these are written to a http.Request
*/
type ListClusterNodesParams struct {

	/*Cluster
	  The identifier of a cluster.

	*/
	Cluster string
	/*NodePool
	  The identifier of a node pool.

	*/
	NodePool string
	/*Org
	  The organization identifier

	*/
	Org string
	/*Project
	  The project identifier

	*/
	Project string
	/*State
	  Filter the nodes by specified states

	*/
	State []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list cluster nodes params
func (o *ListClusterNodesParams) WithTimeout(timeout time.Duration) *ListClusterNodesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list cluster nodes params
func (o *ListClusterNodesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list cluster nodes params
func (o *ListClusterNodesParams) WithContext(ctx context.Context) *ListClusterNodesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list cluster nodes params
func (o *ListClusterNodesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list cluster nodes params
func (o *ListClusterNodesParams) WithHTTPClient(client *http.Client) *ListClusterNodesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list cluster nodes params
func (o *ListClusterNodesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCluster adds the cluster to the list cluster nodes params
func (o *ListClusterNodesParams) WithCluster(cluster string) *ListClusterNodesParams {
	o.SetCluster(cluster)
	return o
}

// SetCluster adds the cluster to the list cluster nodes params
func (o *ListClusterNodesParams) SetCluster(cluster string) {
	o.Cluster = cluster
}

// WithNodePool adds the nodePool to the list cluster nodes params
func (o *ListClusterNodesParams) WithNodePool(nodePool string) *ListClusterNodesParams {
	o.SetNodePool(nodePool)
	return o
}

// SetNodePool adds the nodePool to the list cluster nodes params
func (o *ListClusterNodesParams) SetNodePool(nodePool string) {
	o.NodePool = nodePool
}

// WithOrg adds the org to the list cluster nodes params
func (o *ListClusterNodesParams) WithOrg(org string) *ListClusterNodesParams {
	o.SetOrg(org)
	return o
}

// SetOrg adds the org to the list cluster nodes params
func (o *ListClusterNodesParams) SetOrg(org string) {
	o.Org = org
}

// WithProject adds the project to the list cluster nodes params
func (o *ListClusterNodesParams) WithProject(project string) *ListClusterNodesParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the list cluster nodes params
func (o *ListClusterNodesParams) SetProject(project string) {
	o.Project = project
}

// WithState adds the state to the list cluster nodes params
func (o *ListClusterNodesParams) WithState(state []string) *ListClusterNodesParams {
	o.SetState(state)
	return o
}

// SetState adds the state to the list cluster nodes params
func (o *ListClusterNodesParams) SetState(state []string) {
	o.State = state
}

// WriteToRequest writes these params to a swagger request
func (o *ListClusterNodesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster
	if err := r.SetPathParam("cluster", o.Cluster); err != nil {
		return err
	}

	// path param node_pool
	if err := r.SetPathParam("node_pool", o.NodePool); err != nil {
		return err
	}

	// path param org
	if err := r.SetPathParam("org", o.Org); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	valuesState := o.State

	joinedState := swag.JoinByFormat(valuesState, "")
	// query array param state
	if err := r.SetQueryParam("state", joinedState...); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
