// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListClusterLBsParams creates a new ListClusterLBsParams object
// with the default values initialized.
func NewListClusterLBsParams() *ListClusterLBsParams {
	var (
		stateDefault = []string{"starting", "running", "updating", "terminating", "terminated"}
	)
	return &ListClusterLBsParams{
		State: stateDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewListClusterLBsParamsWithTimeout creates a new ListClusterLBsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListClusterLBsParamsWithTimeout(timeout time.Duration) *ListClusterLBsParams {
	var (
		stateDefault = []string{"starting", "running", "updating", "terminating", "terminated"}
	)
	return &ListClusterLBsParams{
		State: stateDefault,

		timeout: timeout,
	}
}

// NewListClusterLBsParamsWithContext creates a new ListClusterLBsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListClusterLBsParamsWithContext(ctx context.Context) *ListClusterLBsParams {
	var (
		stateDefault = []string{"starting", "running", "updating", "terminating", "terminated"}
	)
	return &ListClusterLBsParams{
		State: stateDefault,

		Context: ctx,
	}
}

// NewListClusterLBsParamsWithHTTPClient creates a new ListClusterLBsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListClusterLBsParamsWithHTTPClient(client *http.Client) *ListClusterLBsParams {
	var (
		stateDefault = []string{"starting", "running", "updating", "terminating", "terminated"}
	)
	return &ListClusterLBsParams{
		State:      stateDefault,
		HTTPClient: client,
	}
}

/*ListClusterLBsParams contains all the parameters to send to the API endpoint
for the list cluster l bs operation typically these are written to a http.Request
*/
type ListClusterLBsParams struct {

	/*Cluster
	  The identifier of a cluster.

	*/
	Cluster string
	/*Org
	  The organization identifier

	*/
	Org string
	/*Project
	  The project identifier

	*/
	Project string
	/*State
	  Filter the load balancers by specified states

	*/
	State []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list cluster l bs params
func (o *ListClusterLBsParams) WithTimeout(timeout time.Duration) *ListClusterLBsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list cluster l bs params
func (o *ListClusterLBsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list cluster l bs params
func (o *ListClusterLBsParams) WithContext(ctx context.Context) *ListClusterLBsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list cluster l bs params
func (o *ListClusterLBsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list cluster l bs params
func (o *ListClusterLBsParams) WithHTTPClient(client *http.Client) *ListClusterLBsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list cluster l bs params
func (o *ListClusterLBsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCluster adds the cluster to the list cluster l bs params
func (o *ListClusterLBsParams) WithCluster(cluster string) *ListClusterLBsParams {
	o.SetCluster(cluster)
	return o
}

// SetCluster adds the cluster to the list cluster l bs params
func (o *ListClusterLBsParams) SetCluster(cluster string) {
	o.Cluster = cluster
}

// WithOrg adds the org to the list cluster l bs params
func (o *ListClusterLBsParams) WithOrg(org string) *ListClusterLBsParams {
	o.SetOrg(org)
	return o
}

// SetOrg adds the org to the list cluster l bs params
func (o *ListClusterLBsParams) SetOrg(org string) {
	o.Org = org
}

// WithProject adds the project to the list cluster l bs params
func (o *ListClusterLBsParams) WithProject(project string) *ListClusterLBsParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the list cluster l bs params
func (o *ListClusterLBsParams) SetProject(project string) {
	o.Project = project
}

// WithState adds the state to the list cluster l bs params
func (o *ListClusterLBsParams) WithState(state []string) *ListClusterLBsParams {
	o.SetState(state)
	return o
}

// SetState adds the state to the list cluster l bs params
func (o *ListClusterLBsParams) SetState(state []string) {
	o.State = state
}

// WriteToRequest writes these params to a swagger request
func (o *ListClusterLBsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster
	if err := r.SetPathParam("cluster", o.Cluster); err != nil {
		return err
	}

	// path param org
	if err := r.SetPathParam("org", o.Org); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	valuesState := o.State

	joinedState := swag.JoinByFormat(valuesState, "")
	// query array param state
	if err := r.SetQueryParam("state", joinedState...); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
