// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListClusterTokensParams creates a new ListClusterTokensParams object
// with the default values initialized.
func NewListClusterTokensParams() *ListClusterTokensParams {
	var ()
	return &ListClusterTokensParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListClusterTokensParamsWithTimeout creates a new ListClusterTokensParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListClusterTokensParamsWithTimeout(timeout time.Duration) *ListClusterTokensParams {
	var ()
	return &ListClusterTokensParams{

		timeout: timeout,
	}
}

// NewListClusterTokensParamsWithContext creates a new ListClusterTokensParams object
// with the default values initialized, and the ability to set a context for a request
func NewListClusterTokensParamsWithContext(ctx context.Context) *ListClusterTokensParams {
	var ()
	return &ListClusterTokensParams{

		Context: ctx,
	}
}

// NewListClusterTokensParamsWithHTTPClient creates a new ListClusterTokensParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListClusterTokensParamsWithHTTPClient(client *http.Client) *ListClusterTokensParams {
	var ()
	return &ListClusterTokensParams{
		HTTPClient: client,
	}
}

/*ListClusterTokensParams contains all the parameters to send to the API endpoint
for the list cluster tokens operation typically these are written to a http.Request
*/
type ListClusterTokensParams struct {

	/*Cluster
	  The identifier of a cluster.

	*/
	Cluster string
	/*Org
	  The organization identifier

	*/
	Org string
	/*Project
	  The project identifier

	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list cluster tokens params
func (o *ListClusterTokensParams) WithTimeout(timeout time.Duration) *ListClusterTokensParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list cluster tokens params
func (o *ListClusterTokensParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list cluster tokens params
func (o *ListClusterTokensParams) WithContext(ctx context.Context) *ListClusterTokensParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list cluster tokens params
func (o *ListClusterTokensParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list cluster tokens params
func (o *ListClusterTokensParams) WithHTTPClient(client *http.Client) *ListClusterTokensParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list cluster tokens params
func (o *ListClusterTokensParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCluster adds the cluster to the list cluster tokens params
func (o *ListClusterTokensParams) WithCluster(cluster string) *ListClusterTokensParams {
	o.SetCluster(cluster)
	return o
}

// SetCluster adds the cluster to the list cluster tokens params
func (o *ListClusterTokensParams) SetCluster(cluster string) {
	o.Cluster = cluster
}

// WithOrg adds the org to the list cluster tokens params
func (o *ListClusterTokensParams) WithOrg(org string) *ListClusterTokensParams {
	o.SetOrg(org)
	return o
}

// SetOrg adds the org to the list cluster tokens params
func (o *ListClusterTokensParams) SetOrg(org string) {
	o.Org = org
}

// WithProject adds the project to the list cluster tokens params
func (o *ListClusterTokensParams) WithProject(project string) *ListClusterTokensParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the list cluster tokens params
func (o *ListClusterTokensParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *ListClusterTokensParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster
	if err := r.SetPathParam("cluster", o.Cluster); err != nil {
		return err
	}

	// path param org
	if err := r.SetPathParam("org", o.Org); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
