// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/EricomSoftwareLtd/ridge-go/models"
)

// ListClusterNodesReader is a Reader for the ListClusterNodes structure.
type ListClusterNodesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListClusterNodesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListClusterNodesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListClusterNodesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewListClusterNodesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListClusterNodesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListClusterNodesOK creates a ListClusterNodesOK with default headers values
func NewListClusterNodesOK() *ListClusterNodesOK {
	return &ListClusterNodesOK{}
}

/*ListClusterNodesOK handles this case with default header values.

Success
*/
type ListClusterNodesOK struct {
	Payload *models.Nodes
}

func (o *ListClusterNodesOK) Error() string {
	return fmt.Sprintf("[GET /orgs/{org}/projects/{project}/clusters/{cluster}/node-pools/{node_pool}/nodes][%d] listClusterNodesOK  %+v", 200, o.Payload)
}

func (o *ListClusterNodesOK) GetPayload() *models.Nodes {
	return o.Payload
}

func (o *ListClusterNodesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Nodes)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListClusterNodesBadRequest creates a ListClusterNodesBadRequest with default headers values
func NewListClusterNodesBadRequest() *ListClusterNodesBadRequest {
	return &ListClusterNodesBadRequest{}
}

/*ListClusterNodesBadRequest handles this case with default header values.

Bad request parameter
*/
type ListClusterNodesBadRequest struct {
	Payload string
}

func (o *ListClusterNodesBadRequest) Error() string {
	return fmt.Sprintf("[GET /orgs/{org}/projects/{project}/clusters/{cluster}/node-pools/{node_pool}/nodes][%d] listClusterNodesBadRequest  %+v", 400, o.Payload)
}

func (o *ListClusterNodesBadRequest) GetPayload() string {
	return o.Payload
}

func (o *ListClusterNodesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListClusterNodesForbidden creates a ListClusterNodesForbidden with default headers values
func NewListClusterNodesForbidden() *ListClusterNodesForbidden {
	return &ListClusterNodesForbidden{}
}

/*ListClusterNodesForbidden handles this case with default header values.

Forbidden
*/
type ListClusterNodesForbidden struct {
	Payload string
}

func (o *ListClusterNodesForbidden) Error() string {
	return fmt.Sprintf("[GET /orgs/{org}/projects/{project}/clusters/{cluster}/node-pools/{node_pool}/nodes][%d] listClusterNodesForbidden  %+v", 403, o.Payload)
}

func (o *ListClusterNodesForbidden) GetPayload() string {
	return o.Payload
}

func (o *ListClusterNodesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListClusterNodesNotFound creates a ListClusterNodesNotFound with default headers values
func NewListClusterNodesNotFound() *ListClusterNodesNotFound {
	return &ListClusterNodesNotFound{}
}

/*ListClusterNodesNotFound handles this case with default header values.

Resource not found
*/
type ListClusterNodesNotFound struct {
	Payload string
}

func (o *ListClusterNodesNotFound) Error() string {
	return fmt.Sprintf("[GET /orgs/{org}/projects/{project}/clusters/{cluster}/node-pools/{node_pool}/nodes][%d] listClusterNodesNotFound  %+v", 404, o.Payload)
}

func (o *ListClusterNodesNotFound) GetPayload() string {
	return o.Payload
}

func (o *ListClusterNodesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
