// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HardwareSpecs hardware specs
//
// swagger:model hardware_specs
type HardwareSpecs struct {

	// The minimal amount of ephemeral storage in MiB in a node.
	EphemeralStorage int32 `json:"ephemeral_storage,omitempty"`

	// The minimal amount of memory in MiB in a node.
	Memory int32 `json:"memory,omitempty"`

	// The preset VM type of the node. Will only be provided if it was specified at creation.
	NodePreset string `json:"node_preset,omitempty"`

	// The minimal number of VCPUs in a node.
	Vcpus int32 `json:"vcpus,omitempty"`
}

// Validate validates this hardware specs
func (m *HardwareSpecs) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HardwareSpecs) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HardwareSpecs) UnmarshalBinary(b []byte) error {
	var res HardwareSpecs
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
