// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// KeyValues key values
//
// swagger:model key_values
type KeyValues map[string]string

// Validate validates this key values
func (m KeyValues) Validate(formats strfmt.Registry) error {
	return nil
}
