// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// QualitySet A set of required qualities. The object maps quality identifiers to values. For qualities defined with no values, the value must be 1.
//
// swagger:model quality_set
type QualitySet map[string]int64

// Validate validates this quality set
func (m QualitySet) Validate(formats strfmt.Registry) error {
	return nil
}
