// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TokenCreate token create
//
// swagger:model token_create
type TokenCreate struct {

	// The display name of this token
	DisplayName string `json:"display_name,omitempty"`

	// The unique identifier of the Ridge member assigned to this token. The member ID will be used as the Kubernetes username. Either member_id or member_path must be specified; if both are present, they must agree.
	MemberID string `json:"member_id,omitempty"`

	// The full path to the Ridge member assigned to this token. The member ID will be used as the Kubernetes username. Either member_id or member_path must be specified; if both are present, they must agree.
	MemberPath string `json:"member_path,omitempty"`

	// The human readable name of this token
	Name string `json:"name,omitempty"`
}

// Validate validates this token create
func (m *TokenCreate) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TokenCreate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TokenCreate) UnmarshalBinary(b []byte) error {
	var res TokenCreate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
